spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driverClassName: org.mariadb.jdbc.Driver

  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database: mysql
  jwt:
    secret: emVyby1iYXNlLWh3LXRhYmxlaW5n
